name: transcipt_whisper_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  whisper_dart:
  file_picker: ^5.2.5
  cool_alert: ^1.1.0
  path_provider: ^2.0.13

flutter:


  uses-material-design: true

  assets:
    - assets/
